### ISSUE TITLE
New Provider set when passing connection string.

### ISSUE THREAD

**Issue by whizlingo** [ycamargo/diagnostics-eventflow-sqloutput#1]
Can you please set the provider name when creating the output from the connection string ?. Currently that is not handled in your code.
 
`ConnectionSettings = new ConnectionStringSettings(nameof(SqlTableOutput), Configuration.ConnectionString, SQLPROVIDER);`

**Comment by ycamargo** [comment]
Hi @whizlingo, sorry for this late response.
Sure I can do it. 
But what's the point? In the way I coded you can put the provider name in your Connection String. I just validate if it is the Sql Server provider (for now because I would love to support different providers in the future).
Why you want this change?

**Comment by ycamargo** [comment]
Hi @whizlingo, I'll close this issue, ok?
